Document: fritzident
Title: Debian fritzident Manual
Author: <insert document author here>
Abstract: This manual describes what fritzident is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fritzident/fritzident.sgml.gz

Format: postscript
Files: /usr/share/doc/fritzident/fritzident.ps.gz

Format: text
Files: /usr/share/doc/fritzident/fritzident.text.gz

Format: HTML
Index: /usr/share/doc/fritzident/html/index.html
Files: /usr/share/doc/fritzident/html/*.html
