.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Nils Naumann <nau@gmx.net>,
.\"
.TH FRITZIDENT 8 "October 27, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fritzident \- parental control for Fritz!Box
.SH SYNOPSIS
.B fritzident
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B fritzident
daemon.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBfritzident\fP is a program that eneabeling the parental control
function of the AVM Fritz!Box. It mimics the standard AVM Windows
application that allows the Fritz!Box to recognize individual users
connecting to the internet.
.br
This application is supposed to run under control of inetd.

.SH Internal working
At startup, fritzident sends out a prompt message, then waits for a
single command, and sends the response.  The prompt message is "AVM
IDENT", and is required for the Fritz!Box to recognize the agent.

Recognized commands:
.IP USERS
return a list of known users
.IP TCP ip:port
return the name of the user for the specified local TCP port
.IP UDP ip:port
idem, but for UDP ports
.PP
The prompt, as well as all replies, are terminated by a CR & NL (ASC
13 + ASC 10). Commands are recognized with either CR & NL or just NL
line termination. This allows fritzident to be tested interactively.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-l, \-\-log file
eneabeling logging into the specified file.
.TP
.B \-d, \-\-domain
fake a Windows domain.
.B \-?, \-\-help
display help.
.SH SEE ALSO
.BR inetd (8).
.br
